service:
  name: github

plugins:
  - serverless-fargate-plugin
  - serverless-dotenv-plugin

provider:
  name: aws
  profile: "default"
  stage: ${opt:stage,'dev'}
  region: ${env:REGION}
  logRetentionInDays: 7
custom:
  dotenv:
    basePath: ./
  ecrImagePath:
    accountNumber: ${env:ACCOUNT_NUMBER}
    region: ${env:REGION}
    imageName: ${env:IMAGE_NAME}
    imageTag: ${env:IMAGE_TAG}
  fargate:
    - clusterName: repositories
      vpc:
        cidr: ${env:CIDR}
        subnets:
          - ${env:SUBNET_ID_1}
          - ${env:SUBNET_ID_2}
      tags:
        customer: You
        owner: Me
      disableELB: false
      services:
        - name: ${env:IMAGE_NAME}
          cpu: 512
          memory: 1024
          port: 4000
          healthCheckUri: /health
          healthCheckInterval: 6
          imageTag: ${self:custom.ecrImagePath.imageTag}
          imageRepository: "${self:custom.ecrImagePath.accountNumber}.dkr.ecr.${self:custom.ecrImagePath.region}.amazonaws.com/${self:custom.ecrImagePath.imageName}"
          autoScale:
            min: 1
            max: 2
            cooldownIn: 30
            cooldownOut: 60
            metric: ECSServiceAverageCPUUtilization
            targetValue: 75
          entryPoint:
            - npm
            - run
            - deploy:dev
          environment:
            PRODUCTION: true
          protocols:
            - protocol: HTTP