AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repository
Resources:
  AWSGitHubInfoRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "github-info"
Outputs:
  AWSGitHubInfoRepositoryArn:
    Value: !GetAtt AWSGitHubInfoRepository.Arn
    Export:
      Name: AWSGitHubInfoRepositoryArn